version: 1.0.{build}

image: Visual Studio 2022

environment:
  JAVA_HOME: C:\Program Files\Java\jdk-17

install:
  - choco install allure.commandline -y
  - refreshenv

build_script:
  - gradlew.bat clean test
  - gradlew.bat allureReport

after_test:
  - allure generate build/allure-results --clean -o build/allure-report
